# Generated by Django 4.2.7 on 2025-05-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_produto_criado_em_remove_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/profile_pics'),
        ),
    ]
